spring:
  application:
    name: pedidos-api

  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos-api
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true